version: "2"

networks:
    traefik:
        external: true
    db:
        external: true
services:
    gitea:
        image: gitea/gitea:latest
        environment:
            - USER_UID=${PUID}
            - USER_GID=${PGID}
            - DB_TYPE=postgres
            - DB_HOST=db
            - DB_NAME=gitea
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWD=${POSTGRES_PASSWORD}
            - VIRTUAL_HOST=git.${HOSTNAME}
            - VIRTUAL_PORT=3000
        restart: always
        networks:
            - traefik
            - db
        volumes:
            - ${DATA_DIR}/gitea/data:/data
        labels:
            - "traefik.backend=gitea"
            - "traefik.docker.network=traefik"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:git.${HOSTNAME}"
            - "traefik.port=3000"
