version: '3.5'
services:
  nextcloud:
    build: .
    image: nextcloud:apache-smb
    # image: "nextcloud:${NEXTCLOUD_VERSION}"
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - "${MEDIA_DIR}:/media"
        #  - "${DATA_DIR}/nextcloud:/var/www/html"
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - traefik 
      - db 
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:cloud.${HOSTNAME}"
      - "traefik.port=80"

  # backups:
  #   image: christophetd/duplicacy-autobackup:v1.0
  #   container_name: backups
  #   restart: always
  #   environment:
  #     BACKUP_NAME: "${BACKUP_NAME}"
  #     BACKUP_LOCATION: "b2://${B2_BUCKET}"
  #     BACKUP_SCHEDULE: "${BACKUP_SCHEDULE}"
  #     BACKUP_ENCRYPTION_KEY: "${BACKUP_ENCRYPTION_KEY}"
  #     B2_ID: "${B2_ID}"
  #     B2_KEY: "${B2_KEY}"
  #   volumes:
  #     - "${DATA_DIR}:/data"

volumes:
  nextcloud:

networks:
  db:
    external: true
  traefik:
    external: true
