version: '3.5'
services:
  db:
    image: mysql:${MYSQL_VERSION}
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db 
    restart: always
    volumes:
      - "${DATA_DIR}/mysql:/var/lib/mysql"
      - "./mysql-init-files:/docker-entrypoint-initdb.d"
    environment: 
      MYSQL_ROOT_PASSWORD: nopassword
    networks:
      - internal

  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
      - "${DATA_DIR}/mysql:/var/lib/mysql"
      - "/mnt:/mnt"
    environment:
      MYSQL_HOST: db 
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: nopassword
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
    depends_on:
      - db 
    networks:
      - traefik 
      - internal
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:backup.janewilde.ga"
      - "traefik.port=80"
  redis:
    image: redis
    container_name: redis
    volumes:
      - "${DATA_DIR}/nextcloud/redis:/data"
    networks:
      - internal

  # backups:
  #   image: christophetd/duplicacy-autobackup:v1.0
  #   container_name: backups
  #   restart: always
  #   environment:
  #     BACKUP_NAME: "${BACKUP_NAME}"
  #     BACKUP_LOCATION: "b2://${B2_BUCKET}"
  #     BACKUP_SCHEDULE: "${BACKUP_SCHEDULE}"
  #     BACKUP_ENCRYPTION_KEY: "${BACKUP_ENCRYPTION_KEY}"
  #     B2_ID: "${B2_ID}"
  #     B2_KEY: "${B2_KEY}"
  #   volumes:
  #     - "${DATA_DIR}:/data"

networks:
  internal:
  traefik:
    external: true
