version: '3.5'
services:
  nextcloud:
    build: .
    image: nextcloud:apache-smb
    # image: "nextcloud:${NEXTCLOUD_VERSION}"
    env_file:
      - ../db.env
    restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
      - "/media:/media"
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
    networks:
      - traefik 
      - db 
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:backup.${HOSTNAME}"
      - "traefik.port=80"
  redis:
    image: redis
    container_name: redis
    volumes:
      - "${DATA_DIR}/nextcloud/redis:/data"
    networks:
      - db 

  # backups:
  #   image: christophetd/duplicacy-autobackup:v1.0
  #   container_name: backups
  #   restart: always
  #   environment:
  #     BACKUP_NAME: "${BACKUP_NAME}"
  #     BACKUP_LOCATION: "b2://${B2_BUCKET}"
  #     BACKUP_SCHEDULE: "${BACKUP_SCHEDULE}"
  #     BACKUP_ENCRYPTION_KEY: "${BACKUP_ENCRYPTION_KEY}"
  #     B2_ID: "${B2_ID}"
  #     B2_KEY: "${B2_KEY}"
  #   volumes:
  #     - "${DATA_DIR}:/data"

networks:
  db:
    driver: overlay
    name: db 
  traefik:
    external: true
