version: '3.5'
services:
  odoo:
    image: odoo:latest
    container_name: odoo
    restart: always
    volumes:
        - ${DATA_DIR}/odoo/addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - VIRTUAL_HOST=odoo.${HOSTNAME}
      - VIRTUAL_PORT=8069
      - LETSENCRYPT_HOST=odoo.${HOSTNAME}
    networks:
        - db 
        - traefik
    labels:
      - "traefik.backend=odoo"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:odoo.${HOSTNAME}"
      - "traefik.port=8069"

networks:
    traefik:
        external: true
    db:
        external: true
