version: '3.5'
services:
  db:
    image: postgres:10
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    #  - "${DATA_DIR}/postgresql:/var/lib/postgresql/data"
       - postgresql:/var/lib/postgresql/data
    networks:
      - db 

networks:
    db:
        driver: overlay
        name: db 

volumes:
  postgresql:
